// src/components/ui/badge.tsx
import React from 'react';

interface BadgeProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'default' | 'secondary' | 'destructive' | 'outline';
  children: React.ReactNode;
}

export const Badge = React.forwardRef<HTMLDivElement, BadgeProps>(
  ({ className = '', variant = 'default', children, ...props }, ref) => {
    const baseClasses = 'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2';
    
    const variants = {
      default: 'border-transparent bg-blue-600 text-white hover:bg-blue-700',
      secondary: 'border-transparent bg-gray-100 text-gray-900 hover:bg-gray-200',
      destructive: 'border-transparent bg-red-600 text-white hover:bg-red-700',
      outline: 'text-gray-900 border-gray-300'
    };
    
    return (
      <div
        ref={ref}
        className={`${baseClasses} ${variants[variant]} ${className}`}
        {...props}
      >
        {children}
      </div>
    );
  }
);

Badge.displayName = 'Badge';

// src/lib/components/ui/badge/badge.svelte
<script lang="ts">
  import type { BadgeVariant } from '$lib/types/ui';
  import { cn } from '$lib/utils';

  // Props del componente
  export let variant: BadgeVariant = 'default';
  export let className = '';

  // Función para crear clases CSS
  function getBadgeClasses(variant: BadgeVariant): string {
    const baseClasses =
      'inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2';

    const variantClasses = {
      default: 'border-transparent bg-primary-600 text-white hover:bg-primary-700',
      secondary: 'border-transparent bg-secondary-200 text-secondary-900 hover:bg-secondary-300',
      destructive: 'border-transparent bg-red-600 text-white hover:bg-red-700',
      outline: 'border-secondary-200 text-secondary-900 hover:bg-secondary-50'
    };

    return cn(baseClasses, variantClasses[variant], className);
  }

  $: badgeClasses = getBadgeClasses(variant);
</script>

<div class={badgeClasses} {...$$restProps}>
  <slot />
</div>
