// client/pages/Login.tsx
import { useState } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useNavigate, Navigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, Eye, EyeOff } from "lucide-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { toast } from "@/hooks/use-toast";

// Schema de validación para el formulario
const loginSchema = z.object({
  email: z
    .string()
    .min(1, "El email es requerido")
    .email("Ingresa un email válido"),
  password: z
    .string()
    .min(6, "La contraseña debe tener al menos 6 caracteres"),
});

type LoginFormData = z.infer<typeof loginSchema>;

export default function Login() {
  const [showPassword, setShowPassword] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { login, isAuthenticated, isLoading } = useAuth();
  const navigate = useNavigate();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginFormData>({
    resolver: zodResolver(loginSchema),
  });

  // Si ya está autenticado, redirigir al dashboard
  if (isAuthenticated) {
    return <Navigate to="/" replace />;
  }

  // Mostrar loader mientras verifica autenticación
  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-950 text-white">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="h-8 w-8 animate-spin" />
          <p className="text-gray-400">Verificando sesión...</p>
        </div>
      </div>
    );
  }

  const onSubmit = async (data: LoginFormData) => {
    try {
      setIsSubmitting(true);
      await login(data);
      navigate("/", { replace: true });
    } catch (error) {
      // El error ya se maneja en el AuthContext
      console.error("Login error:", error);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-950 text-white p-4">
      <div className="w-full max-w-md">
        <Card className="bg-gray-900 border-gray-800">
          <CardHeader className="text-center">
            <CardTitle className="text-2xl font-bold text-white">
              UTalk
            </CardTitle>
            <p className="text-gray-400 text-sm mt-2">
              Inicia sesión en tu cuenta
            </p>
          </CardHeader>
          
          <CardContent>
            <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
              {/* Campo Email */}
              <div className="space-y-2">
                <Label htmlFor="email" className="text-gray-200">
                  Email
                </Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="tu@email.com"
                  className="bg-gray-800 border-gray-700 text-white placeholder-gray-500 focus:border-blue-500"
                  {...register("email")}
                />
                {errors.email && (
                  <p className="text-red-400 text-sm">{errors.email.message}</p>
                )}
              </div>

              {/* Campo Contraseña */}
              <div className="space-y-2">
                <Label htmlFor="password" className="text-gray-200">
                  Contraseña
                </Label>
                <div className="relative">
                  <Input
                    id="password"
                    type={showPassword ? "text" : "password"}
                    placeholder="Tu contraseña"
                    className="bg-gray-800 border-gray-700 text-white placeholder-gray-500 focus:border-blue-500 pr-10"
                    {...register("password")}
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    className="absolute right-0 top-0 h-full px-3 hover:bg-transparent"
                    onClick={() => setShowPassword(!showPassword)}
                  >
                    {showPassword ? (
                      <EyeOff className="h-4 w-4 text-gray-400" />
                    ) : (
                      <Eye className="h-4 w-4 text-gray-400" />
                    )}
                  </Button>
                </div>
                {errors.password && (
                  <p className="text-red-400 text-sm">{errors.password.message}</p>
                )}
              </div>

              {/* Botón Submit */}
              <Button
                type="submit"
                className="w-full bg-blue-600 hover:bg-blue-700 text-white"
                disabled={isSubmitting}
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Iniciando sesión...
                  </>
                ) : (
                  "Iniciar Sesión"
                )}
              </Button>
            </form>

            {/* Información adicional */}
            <div className="mt-6 text-center">
              <p className="text-gray-400 text-sm">
                ¿Olvidaste tu contraseña?{" "}
                <button
                  type="button"
                  className="text-blue-400 hover:text-blue-300 underline"
                  onClick={() => {
                    toast({
                      title: "Funcionalidad pendiente",
                      description: "La recuperación de contraseña estará disponible pronto.",
                    });
                  }}
                >
                  Recupérala aquí
                </button>
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Información de desarrollo */}
        {import.meta.env.DEV && (
          <div className="mt-4 p-4 bg-gray-800 rounded-lg border border-gray-700">
            <p className="text-gray-400 text-xs text-center mb-2">
              <strong>Modo de desarrollo</strong>
            </p>
            <p className="text-gray-500 text-xs text-center">
              Credenciales de prueba: admin@utalk.com / 123456
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

// src/routes/login/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { httpPost } from '$lib/api/http';
  import Button from '$lib/components/ui/button/button.svelte';
  import CardContent from '$lib/components/ui/card/card-content.svelte';
  import CardHeader from '$lib/components/ui/card/card-header.svelte';
  import CardTitle from '$lib/components/ui/card/card-title.svelte';
  import Card from '$lib/components/ui/card/card.svelte';
  import Input from '$lib/components/ui/input/input.svelte';
  import { authStore, setAccessToken } from '$lib/stores/auth.store';

  // Variables reactivas
  let email = '';
  let password = '';
  let loading = false;
  let error = '';

  // ✅ PETICIÓN DIRECTA AL BACKEND - SIN SERVER ACTIONS
  async function handleLogin() {
    if (!email || !password) {
      error = 'Email y contraseña son requeridos';
      return;
    }

    loading = true;
    error = '';

    try {
      // eslint-disable-next-line no-console
      console.log('🚀 LOGIN CLIENT - Iniciando autenticación directa al backend');

      const payload = { email, password };
      const data = await httpPost<any>('auth/login', payload); // <-- no '/api/'

      // eslint-disable-next-line no-console
      console.log(
        '🔍 LOGIN CLIENT - Respuesta completa del backend:',
        JSON.stringify(data, null, 2)
      );

      // Validar respuesta del backend
      if (!data || !data.success || !data.accessToken) {
        // eslint-disable-next-line no-console
        console.warn('⚠️ LOGIN CLIENT - Respuesta inválida del backend');
        if (!data?.accessToken) {
          throw new Error(
            'Login OK pero sin accessToken en el body. Revisa nombre del campo en back.'
          );
        }
        error = 'Credenciales incorrectas';
        return;
      }

      // Preparar datos del usuario según la estructura real del backend
      const user = {
        id: data.user.id,
        email: data.user.email,
        name: data.user.name,
        role: data.user.role,
        isActive: data.user.isActive,
        phone: data.user.phone,
        permissions: data.user.permissions || [],
        department: data.user.department,
        settings: data.user.settings,
        lastLoginAt: data.user.lastLoginAt,
        createdAt: data.user.createdAt,
        updatedAt: data.user.updatedAt,
        performance: data.user.performance
      };

      // Guardar el accessToken
      setAccessToken(data.accessToken);

      // Actualizar el store de autenticación
      authStore.login(user, data.accessToken, data.refreshToken);

      // eslint-disable-next-line no-console
      console.log('✅ LOGIN CLIENT - Exitoso para:', user.email);

      // Redirigir al dashboard después del login exitoso
      goto('/dashboard');
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error('🚨 LOGIN CLIENT - Error crítico:', err);
      error = 'Error de conexión. Intenta nuevamente.';
    } finally {
      loading = false;
    }
  }

  // Manejar submit del formulario
  function handleSubmit(event: any) {
    event.preventDefault();
    handleLogin();
  }
</script>

<svelte:head>
  <title>Iniciar Sesión - UTalk</title>
  <meta name="description" content="Inicia sesión en UTalk" />
</svelte:head>

<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
  <Card class="w-full max-w-md">
    <CardHeader class="text-center">
      <CardTitle class="text-2xl font-bold text-gray-900">Iniciar Sesión en UTalk</CardTitle>
      <p class="text-gray-600 mt-2">Ingresa tus credenciales para acceder al sistema</p>
    </CardHeader>

    <CardContent>
      <!-- Mostrar errores si existen -->
      {#if error}
        <div class="mb-4 p-3 bg-red-50 border border-red-200 rounded-md">
          <p class="text-red-800 text-sm">{error}</p>
        </div>
      {/if}

      <!-- Formulario de login -->
      <form on:submit={handleSubmit} class="space-y-4">
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700 mb-1"> Email </label>
          <Input
            id="email"
            name="email"
            type="email"
            bind:value={email}
            required
            disabled={loading}
            placeholder="tu@email.com"
            class="w-full"
          />
        </div>

        <div>
          <label for="password" class="block text-sm font-medium text-gray-700 mb-1">
            Contraseña
          </label>
          <Input
            id="password"
            name="password"
            type="password"
            bind:value={password}
            required
            disabled={loading}
            placeholder="••••••••"
            class="w-full"
          />
        </div>

        <Button type="submit" disabled={loading || !email || !password} className="w-full">
          {#if loading}
            <div class="flex items-center gap-2">
              <div
                class="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"
              ></div>
              Iniciando sesión...
            </div>
          {:else}
            Iniciar Sesión
          {/if}
        </Button>
      </form>

      <div class="mt-4 text-center">
        <p class="text-sm text-gray-600">¿Problemas para acceder? Contacta al administrador</p>
      </div>
    </CardContent>
  </Card>
</div>
