// src/lib/components/ui/input/input.svelte
<script lang="ts">
  import type { InputType } from '$lib/types/ui';
  import { cn } from '$lib/utils';

  // Props del componente
  export let type: InputType = 'text';
  export let placeholder: string | undefined = undefined;
  export let value: string = '';
  export let disabled = false;
  export let readonly = false;
  export let required = false;
  export let autocomplete = undefined;
  export let className = '';

  // Clases CSS para el input
  const inputClasses =
    'flex h-10 w-full rounded-md border border-secondary-200 bg-white px-3 py-2 text-sm ring-offset-white file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-secondary-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50';
</script>

<input
  class={cn(inputClasses, className)}
  {type}
  {placeholder}
  bind:value
  {disabled}
  {readonly}
  {required}
  {autocomplete}
  {...$$restProps}
/>

// src/components/ui/input.tsx
import React from 'react';

interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  className?: string;
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className = '', type = 'text', ...props }, ref) => {
    const baseClasses = 'flex h-10 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-gray-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50';
    
    return (
      <input
        type={type}
        className={`${baseClasses} ${className}`}
        ref={ref}
        {...props}
      />
    );
  }
);

Input.displayName = 'Input';
